export const FETCH_PIZZA_START = "FETCH_PIZZA_START";
export const FETCH_PIZZA_SUCCESS = "FETCH_PIZZA_SUCCESS";
export const FETCH_PIZZA_ERR = "FETCH_PIZZA_ERR";

export const LOAD_PIZZA_START = "LOAD_PIZZA_START"
export const LOAD_PIZZA_SUCCESS = "LOAD_MORE_PIZZA"
export const LOAD_PIZZA_ERR = "LOAD_PIZZA_ERR"

export const FETCH_PIZZA_BY_ID_START = "FETCH_PIZZA_BY_ID_START"
export const FETCH_PIZZA_BY_ID_SUCCESS = "FETCH_PIZZA_BY_ID_SUCCESS"
export const FETCH_PIZZA_BY_ID_ERR = "FETCH_PIZZA_BY_ID_ERR"

export const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART"

export const REMOVE_PIZZA_FROM_CART = "REMOVE_PIZZA_FROM_CART"

export const CLEAN_CART = "CLEAN_CART"

export const SEARCH_PIZZA_BY_NAME_START = "SEARCH_PIZZA_BY_NAME_START"
export const SEARCH_PIZZA_BY_NAME_SUCCESS = "SEARCH_PIZZA_BY_NAME_SUCCESS"
export const SEARCH_PIZZA_BY_NAME_ERR = "SEARCH_PIZZA_BY_NAME_ERR"
