export const FETCH_PIZZA_START = "FETCH_PIZZA_START";
export const FETCH_PIZZA_SUCCESS = "FETCH_PIZZA_SUCCESS";
export const FETCH_PIZZA_ERR = "FETCH_PIZZA_ERR";

export const LOAD_PIZZA_START = "LOAD_PIZZA_START"
export const LOAD_PIZZA_SUCCESS = "LOAD_MORE_PIZZA"
export const LOAD_PIZZA_ERR = "LOAD_PIZZA_ERR"